### ISSUE TITLE
Access server request in tokenCallbackFunction to set cookies

### ISSUE THREAD

**Issue by Wintersboy** [whatadewitt/yahoo-fantasy-sports-api#114]
Would it be possible to access the server request (req) in the `tokenCallbackFunction`? This would be extremely helpful as then I could just set the new `access_token` into `req.cookies` in the callback. 

Right now I'm struggling with the flow of refreshing the token and saving it into my cookies. I'm iffy with the process of saving the token into my database in the token callback, as then I have to fetch those tokens on every request to ensure I have the most up-to-date/valid tokens. 

Unless I'm missing something here, the flow is kind of difficult to implement in my case.

**Comment by whatadewitt** [comment]
Hi! Not sure if I have it documented well, or clearly, or at all, but looking at the source you can set the "tokenCallbackFunction" which will be called when the refresh token is refreshed... https://github.com/whatadewitt/yahoo-fantasy-sports-api/blob/master/YahooFantasy.mjs#L210-L213

Would this help you accomplish what you're looking to do?

**Comment by Wintersboy** [comment]
So yes this is exactly what I'm talking about. But in this callback, you only have access to the `access_token` and the `refresh_token` (as far as I can see). It would be really useful if in this callback we had access to `req` so I could update my cookies like this: `req.cookies.token = access_token`.

Again, not sure if this is the best approach as I may be missing something. But for me, this would be the simplest way to persist the tokens.

**Comment by whatadewitt** [comment]
So you want to persist them so they can be accessed on the frontend of your app? You could simply persist them to a data store at that point and then use a cookie you have more control over in your application to be able to pull the token data from the store.

Looking at the docs site, I think I have something set up similarily, but I couldn't tell you why I would have done it this way 2 years ago (assuming its because it was already mostly done this way).

https://github.com/whatadewitt/fantasy-docs-next/blob/fa46e26aba5e4ba40dde51dd1c9c9751fde36aa3/pages/api/auth/callback.js#L15-L43

**Comment by Wintersboy** [comment]
I don't need to access it in the frontend. I'm doing an httpOnly cookie just like in your example. 

I feel like I may not be explain my scenario well enough, **so here's my flow:**

1. Login and set user details/tokens in http only cookie. Works great.
```
yf.authCallback(req, async (err, { access_token, refresh_token }) => {

  ... do stuff ...

      yf.setUserToken(access_token);
      yf.setRefreshToken(refresh_token);

  ... do more stuff ...

      const userData = {
        username,
        oauthId,
        email,
        access_token,
        refresh_token,
        accountId: account._id
      };

      res.cookie('user', userData, COOKIE_SETTINGS); <-- set user info and token in httpOnly cookie
```
2. Every endpoint I use that involves Yahoo Fantasy I grab the `access_token` from the cookie and set it via `setUserToken`. Works great.

**Endpoint:** 
```
router.get('/leagues', async (req, res) => {
  const { access_token } = req.cookies.user || {};

  try {
    const leaguesWithTeams = await getYahooLeagues(access_token);

    res.status(200).json(leaguesWithTeams);
  } catch (err) {
    console.log('err :>> ', err);
    res.status(200).json({ error: err.message || err.description, success: false, });
  }
})
```
**getYahooLeagues function:**
```
const getYahooLeagues = async (access_token) => {
  try {
    yf.setUserToken(access_token);
    const userGames = await yf.user.games();

   ... do stuff ...
```

3. Access token expires. No problem, the auto refresh token takes care of that. However, I can't get the new access_token and refresh_token from the `tokenCallbackFunction` back into my cookie because the `tokenCallbackFunction` doesn't have direct access to the `req` ( it's outside the endpoint ).

I want to stay away from always fetching the database to grab the access/refresh tokens for each call. However, it may not be the worst thing in the world to do so? 

I hope this write up explains what I'm trying to do.

**Comment by Wintersboy** [comment]
^ Last thing to bounce off of my previous comment:

It would be cool to somehow know if the access_token was expired without having to make a failed request. Then that way I could fetch the refresh_token from my db, manually refresh the token, and update my cookies, all inside of an express middleware before each call.

**Comment by whatadewitt** [comment]
Hmmm interesting... I think I understand it all (as much as I can over a Github issues thread)

Do you have the code that I can take a peek at? Watching it break might help inspire me on how to do this better (to be honest this thing breaking is how I have devellped pretty much every feature 🤣 )

**Comment by Wintersboy** [comment]
Hahah that's development in a nutshell, isn't it? 😆 

Here's a codeshare of the main logic for authentication and accessing the libraries. [Link](https://codeshare.io/644Xwg)

If you need more info let me know! I really appreciate your time.

**Comment by whatadewitt** [comment]
I realized my docs page was not properly refreshing the token (normally I don't like to wait the hour because... time...)

I just created this PR which I am going to merge in, but can you follow something like this and access the req in the function this way?

**Comment by Wintersboy** [comment]
Yes, this would work! My only concern here is recreating the YahooFantasy class on every call. Would this be suboptimal, or would it not make much difference?

**Comment by whatadewitt** [comment]
I mean, I know what you're getting at, but unless you're getting an insane amount of traffic it should be fine, the instances should be garbage collected whenever that happens and I don't believe there's anything that will remain kicking around in memory afterwards.

That said, if you find a situation where this is leading to a clear memory issue for me, submit another issue and we can figure it out!

**Comment by Wintersboy** [comment]
Okay great! Was just making sure. Thanks so much for your help I really appreciate it. The callback function expects a promise right?

**Comment by whatadewitt** [comment]
Congrats! Shoot me a message with what you're building when its done!

**Comment by Wintersboy** [comment]
Hey Luke! So when we last talked you said to let you know when my project was done. Well it's far from done but I finally released the beta! So feel free to go check it out at [Stathound.app](www.stathound.app)

Let me know what you think so far if you end up checking it out 😊

**Comment by whatadewitt** [comment]
Looks really nice! Unfortunately I don't play much Fantasy Hockey anymore so I am getting an error on sign-in 🤣 

Congrats and good luck with it!
