### ISSUE TITLE
Does this still work for anyone? I'm getting OAuth oauth_problem="token_rejected"

### ISSUE THREAD

**Issue by bhays7** [whatadewitt/yahoo-fantasy-sports-api#118]
I started getting this yesterday.

`{
  "lang": "en-US",
  "description": "Please provide valid credentials. OAuth oauth_problem=\"token_rejected\", realm=\"yahooapis.com\""
}`

It doesn't appear to limited to your code. I contacted Yahoo Fantasy Care and they just referred me to the very old documentation.

**Comment by HappyZombies** [comment]
Huh that's funny, I was JUST hitting this same problem today when I tried doing stuff today. Yesterday and the days before the API worked but now it doesn't?

**Comment by clintrorick** [comment]
Yeah, it's not just you.  This has been vexing me all day, and it's not limited to this library - happens across yfpy, connected google sheets, etc.

**Comment by HappyZombies** [comment]
Ok good, I thought was going crazy and maybe I was banned or something lol -- perhaps it's an outage of some sort? Just guessing here...

**Comment by HappyZombies** [comment]
This was very disheartening to not get this to work anymore... I was making so much progress on my app :(

But anyways, I gave up, tried a bunch of different ways. I sent an email according to this page here: https://developer.yahoo.com/sign-in-with-yahoo/#developer-support

We will see ...

**Comment by HappyZombies** [comment]
I tried lots of different things today... all I can say is this, it appears to be that the "https://api.login.yahoo.com/oauth2/get_token" endpoint with the authorization_code grant is returning a wrong token. However the refresh token is valid/correct, and I was able to call the same endpoint with a refresh_token grant, and I am able to get proper and correct access_tokens!!! I can use these to send send successful requests now, so I got it working..for now. 🤷 

So a temporary fix for now is to simply call the refresh token method/endpoint as soon as you authenticate, but the one from the authorization_code is not returning a valid access_token.

**Comment by mostrows2** [comment]
> 
> So a temporary fix for now is to simply call the refresh token method/endpoint as soon as you authenticate, but the one from the authorization_code is not returning a valid access_token.

Can you please elaborate exactly as to what you mean by this?
I can call the "refresh_access_token()" method, but that doesn't affect anything.  A working code snipped would be appreciated.

**Comment by HappyZombies** [comment]
Sure thing, so if you are using this wrapper, I have done something similar to this in my app now and it's working. 😄 

```js
const YahooFantasy = require('yahoo-fantasy');
const express = require('express');
const util = require('util');
const yf = new YahooFantasy(
    "REPLACE_ME",
    "REPLACE_ME",
    () => { },
    "REPLACE_ME"
);


const app = express();
// assuming an express app...
app.get("/auth/yahoo", (req, res) => {
    yf.auth(res);
});


app.get("/callback", (req, res) => {
    yf.authCallback(req, async (err) => {
        if (err) {
            return res.redirect("/error");
        }
        // call refresh_token immediately since it seems that the token sent back with the authorization_code grant is bugged.
        const refreshTokenPromise = util.promisify(yf.refreshToken.bind(yf)); // NOTE: You don't have to do this, but I like to promisify it.
        const yahooResult = await refreshTokenPromise(); // will set an access_token that actually works now.
        const game = await yf.game.meta("nfl");
        return res.json({yahooResult, game}); 
    });
});

```

**Comment by bhays7** [comment]
@HappyZombies can't thank you enough!

**Comment by matt-sales** [comment]
@HappyZombies Thanks for this... It's one of the only workarounds I haven't tried yet. I also emailed Yahoo with my findings but have yet to hear back. I've been a consumer of this API now since the early days of it's release. It seems like once a year I experience an issue like this that magically fixes itself in a few days. Crossing fingers Yahoo makes a fix soon.

**Comment by bhays7** [comment]
Note from Yahoo Fantasy Care, "Our engineering team believes they have fixed this issue. Can you confirm that it works correctly now?"

I tried it and it works for me.

**Comment by HappyZombies** [comment]
Yay!!!!! seems to work now, man that was annoying -- @bhays7 who/where did you contact Yahoo exactly? I e-mailed them at 
siwy@yahooinc.com but got no answer back at all. Would like to know for next time this happens.

Either way, I am going to add the workaround as a backup just in case this happens again. So I'll send a test API request, if it doesn't work I'll send a refresh_token request.

Thanks everyone!

**Comment by bhays7** [comment]
> Yay!!!!! seems to work now, man that was annoying -- @bhays7 who/where did you contact Yahoo exactly? I e-mailed them at [siwy@yahooinc.com](mailto:siwy@yahooinc.com) but got no answer back at all. Would like to know for next time this happens.
> 
> Either way, I am going to add the workaround as a backup just in case this happens again. So I'll send a test API request, if it doesn't work I'll send a refresh_token request.
> 
> Thanks everyone!

@YahooFantasyCC on Twitter

**Comment by whatadewitt** [comment]
Life has been really busy, glad it appears to be sorted! Thanks for the code help @HappyZombies !!

Closing this issue.
