### ISSUE TITLE
Yahoo User not pulling back all leagues

### ISSUE THREAD

**Issue by jmtimper** [whatadewitt/yahoo-fantasy-sports-api#120]
Hey team,

This may be a user error question, but when making a request using the package to fetch user league, some users say they are not seeing all leagues get pulled back. When I'm logging in, I see this user has one linked 2024 NFL league, but they have multiple on their app. 

The accounts that have been impacted seem to be older Yahoo accounts. IDK if that impacts it.

I'm curious if this is something others have encountered something like this where some leagues are not being pulled or if there is some sort of discord/group chat where I could get some more insight. 

Code sample, I try both manually logging in and through the package.
```
   const refreshToken = util.promisify(yf.refreshToken.bind(yf));
        const yahooResult = await refreshToken();
        const accessToken = yahooResult.access_token;
        // Auth success now lets pull leagues
        const resJSON = await MakeYahooRequest('users;use_login=1/games/teams', accessToken, refreshToken);
        const userArr = resJSON?.root?.fantasy_content?.users;
        const users = Array.isArray(userArr.user) ? userArr?.user : [userArr.user];
        console.log("----------------------------NPM PACKAGE------------------------\n")
        try {
          const players = await yf.user.games();
          console.log(players)
          for (game of players?.games) {
            const team = await yf.user.game_teams(game?.game_key);
            console.log(team)
          }
        } catch (err) {
          console.error("Error fetching user data:", err);
        }
```

**Comment by whatadewitt** [comment]
@jmtimper hmmm it looks like you're using you're own Yahoo! wrapper with taht "MakeYahooRequest" function -- what happens if you use the tester on the docs site here: https://yahoo-fantasy-node-docs.vercel.app/resource/user/game_teams (obviously you'll have to login)

One thing that stands out is you're calling "games/teams" which requires you to enter a game key, and on your call I don't see a key specified in that request, but again, you appear to be using a "MakeYahooRequest" function that is custom and not something that is built into this wrapper...

**Comment by jmtimper** [comment]
@whatadewitt Thanks for the reply. So I tried both ways, using my own wrapper and the yf.user.games(). Both requests only returned the same value. I wanted to try both since my own auth was causing issues earlier this month but y'all's handled it perfectly. The games() request only returns 1 2024 league but the test user has 3.

**Comment by whatadewitt** [comment]
Silly question, it's 3 leagues of the same sport? Do you see them all if you query the user leagues resource? I think you're usings the games.user collection right now?

**Comment by jmtimper** [comment]
Wait you may have made it click for me. So Yahoo groups all leagues under the game_key. I'll try using game_leagues for the NFL game key.

I.e. Each team is one of their own teams in a different league.

**Comment by whatadewitt** [comment]
That would likely be it.

Worth noting you can use multiple game keys in a single request... so `mlb,nfl` will give you all of the current baseball and football teams. If you need to go into the past you'll need to use the game_key, which is a numeric identifier of the sport/season in question. I'm going to mark this as closed but let me know if you're still looking for answers!
