### ISSUE TITLE
players stats returns empty stats for specific date

### ISSUE THREAD

**Issue by tanierell** [whatadewitt/yahoo-fantasy-sports-api#121]
I have been trying to fetch some players' stats at a given date from last season, and it returns '-' for all the stats, excluding small amount of players which receive the true stats. is there a problem with yahoo's api?

**Comment by whatadewitt** [comment]
can you share the sport, player, and date in question?

you could also try entering the information here https://yahoo-fantasy-node-docs.vercel.app/resource/player/stats which is basically a raw implementation of the library so it might point to whether there's something wrong in your code or this library.

**Comment by tanierell** [comment]
I have verified it their too, for example looking for NBA, players id 5317, on the 2023-10-25.

**Comment by whatadewitt** [comment]
What is the game key you are using? I see the data for 428.p.5317

My guess is you're using nba.p.5317?

**Comment by tanierell** [comment]
Indeed that was the problem, thank you

**Comment by whatadewitt** [comment]
It's frustrating. When you're using the "current" season, you can default to the league key (nba, mlb, nhl), but if you're using a past season you need to use the game key for THAT season to get stats from that year.

Glad it's sorted :)
