### ISSUE TITLE
No longer able to log-in to Yahoo on demo site

### ISSUE THREAD

**Issue by LudicrousLiam** [whatadewitt/yahoo-fantasy-sports-api#62]
Recently I have not been able to log in on the demo site, which I use semi-frequently to explore the possibilities of this API. Here is what I see when trying to log-in:

https://i.imgur.com/tttSM1v.png

**Comment by WhosNickDoglio** [comment]
Also seeing the same thing 👀

Any progress on this?

**Comment by whatadewitt** [comment]
Hey @LudicrousLiam and @WhosNickDoglio, apologies for the delay. Not getting notifications in my email :S

There's a new and improved site for this:

https://yahoo-fantasy-node-docs.vercel.app/
