### ISSUE TITLE
Is it possible to get the BASE stats that make up a COMPOSITE stat via H2H matchups?

### ISSUE THREAD

**Issue by chrisk1250** [whatadewitt/yahoo-fantasy-sports-api#76]
I use this API route very heavily to aggregate matchup data for my league: https://yahoo-fantasy-node-docs.vercel.app/resource/league/scoreboard

Do you know if it's possible to also obtain the data that goes into the composite stats at the same time? For example, within this API call, I would absolutely love to get all the stuff that makes up OPS. I know Yahoo has it all behind the scenes! Does anyone know of a way to do this at all?

Are you only able to obtain the stat categories that are defined on your league? Or is there some documented/undocumented way to also request specific stat categories as well?

**Comment by whatadewitt** [comment]
In the ultimate "good news/bad news" I have an answer for you!

I do have an answer for you, but that answer is that it's currently not possible.

Luckily I've been able to contact some of the dev team who works at Yahoo! and they've been super responsive to my requests. I asked about exactly this about a month ago, but for AVG, getting the H/ABs for the whole season and not just a week.

The response I got was, "I can't make the API changes you need at this moment but I'll file a ticket to have us look into being able to request all base stats in addition to scoring stats. Word of caution: we won't get this change done any time soon, but I want to make sure it's captured in our backlog."

Hopefully not too long, though!!

(As an aside, I'd love to see some of the stuff you're building with this!!)

**Comment by chrisk1250** [comment]
@whatadewitt Thanks for the quick response on this, glad to know I'm not the only one! Sucks that it's not available, but good to know it's at least on their radar. Okay so we have this dynasty league that's been going on since 2014. We have a Constitution, Keeper Contracts, a Competition Committee--it's intense.

So I've been aggregating all of our matchup stats since inception. There's some really cool insights to be learned. Namely, the standings are massively determined by matchup luck. But with our tool, we're able to determine what your win % might look like if you played all other teams? What if other teams played your schedule? What if we simulated the league 75K times? What if every week instead of playing one team, you played all teams? Pretty interesting stuff!

https://www.zenandtheartofbaseballmaintenance.com/

**Comment by whatadewitt** [comment]
Hah! That's awesome! I'm currently building something similar in my spare time (when I'm not playing video games :S) where it basically breaks down each week by Roto scoring and then I was going to do a "if you played all teams", as well as a "if you played PERSONX's schedule instead of your own" (schedule swap) and a "play this person every week" (for side bet purposes :D)

Mind you, what you have has cool graphs and I like that! Glad you're finding it useful!!

**Comment by chrisk1250** [comment]
We have a striking number of similarities here! 

I'm doing "H2H against every single team every week", "What if someone else had your schedule?", "What if you had someone else's schedule?": https://www.zenandtheartofbaseballmaintenance.com/years/2021/matchups/13

I also can't believe you mentioned side betting. We also have a side pot in the league and it's completely based on a team's record if they played every other team. The number one team each week takes the pot: https://www.zenandtheartofbaseballmaintenance.com/years/2021/roto/rankings

**Comment by whatadewitt** [comment]
Hah, turns out a lot of fantasy players are also degenerate gamblers 😂😂😂😂

**Comment by whatadewitt** [comment]
I'm working on opening up the roto stuff so anyone can use it -- I have it working but need to host it somewhere...
