### ISSUE TITLE
Do Yahoo API reference docs still exist?

### ISSUE THREAD

**Issue by charlietfl** [whatadewitt/yahoo-fantasy-sports-api#77]
I've had numerous iterations of a personal Yhoo fantasy app for quite a few years using a php proxy api and React front end that allows me to see numerous teams in one view and do drag/drop moves , drop players etc

It broke last year when they sunset the social API and I didn't have time to mess with it. I got it working again this weekend but am dumfounded at the docs they provide. The overview "Guide" was always an awful poorly constructed document and I used to rely on the "Reference" docs that detailed all the sub resources and specific paths. That seems to have disappeared and this node app seems to be the best reference left for those resources.

Does anyone know if the full reference docs still exist? They used to be at https://developer.yahoo.com/fantasysports/guide/game-resource.html but that is now a 404

**Comment by shepsii** [comment]
is this what you're looking for? https://developer.yahoo.com/fantasysports/guide/

**Comment by charlietfl** [comment]
@shepsii No. That is the horrible document I mentioned. They used to have a much better organized resource reference beyond that guide page. It had a sidebar with all the various collections/resources and a clean display of all options available for each

**Comment by shepsii** [comment]
@charlietfl the wayback machine has something on your link: https://web.archive.org/web/20130820114739/http://developer.yahoo.com/fantasysports/guide/game-resource.html don't know how helpful that would be!

**Comment by charlietfl** [comment]
@shepsii Never thought of that! Great thinking. It's sure a lot easier to work with than the horrible guide they have all in one page with no navigation. The single page version doesn't appear to be as complete either

**Comment by whatadewitt** [comment]
Thanks @shepsii 

Those are actually the docs that I built all of this off of and contain a bunch of little things that aren't documented in the newer docs.

I've also been privy to some updated docs shared by a contact I have at Yahoo! and there's really not anything that I am missing (outside of things that are going to be made more public very soon)

If there's anything specific you're looking for, please let me know!

**Comment by whatadewitt** [comment]
Closing as I've heard they're not supporting this publicly anymore :(
