### ISSUE TITLE
Get Scores By Player if they were in the starting roster

### ISSUE THREAD

**Issue by CallSign-Filter** [whatadewitt/yahoo-fantasy-sports-api#82]
I am using this for football and in my league we do weekly payouts for different things, for example:

- Week 7, most combined points by all running backs in starting roster
- Week 8, most combined points by all wide receivers in starting roster
- ...
- Week 12 Most combined points by all running backs in starting roster season combined.

I know I can pull the points for each individual player but I didn't see a flag for if they were in the starting roster or not

**Comment by whatadewitt** [comment]
My guess is you'd need to check against the `team.roster` resource for the given week... Does that help?

**Comment by CallSign-Filter** [comment]
Yes it does. Thank you!

That is just the second part of the app I am building. The first part is what I talked about with you 2 years ago; making a live scoring display on a Raspberry PI so I don't have to check my phone on game day. I will keep you updated.

Thank you for all your work, not all heroes wear capes, but you should probably get one anyways

**Comment by whatadewitt** [comment]
That's awesome! Please share the code when you're done! I'd love to check it out!
