### ISSUE TITLE
Importing Offline Draft Resutls

### ISSUE THREAD

**Issue by uythoang** [whatadewitt/yahoo-fantasy-sports-api#83]
My league just completed an offline draft and I have all the data stored in a Postgres table. Is it possible to import the results into Yahoo Fantasy Sports using the API?

**Comment by whatadewitt** [comment]
Unfortunately it doesn't look like that is supported by Yahoo! and certainly isn't currently supported in this wrapper

https://developer.yahoo.com/fantasysports/guide/
