### ISSUE TITLE
Limit to returned row in Players Collection?

### ISSUE THREAD

**Issue by rdbaron** [whatadewitt/yahoo-fantasy-sports-api#91]
Hello!

I'm trying to use Collections for the first time and I'm wondering if the behaviour I'm seeing is expected, or if I'm just doing something wrong.

I'm trying to use players.leagues(league_id) and I am only getting back 25 players from that league.  I can use the `count` filter to retrieve fewer than 25, but setting it higher than 25 does not increase the number returned.

Is this expected?

If so, is there a better way to retrieve all players in a given league than iterating through each roster for each week and collecting them that way?

**Comment by rdbaron** [comment]
I notice I can manually page through the results using the `start` filter, but I'm still wondering if there is a better way.

**Comment by rdbaron** [comment]
Looks like this is the expected behaviour, and the best known solution.

**Comment by whatadewitt** [comment]
Sorry I missed this, but glad you got it sorted :)

**Comment by petegriffith** [comment]
So if I'm understanding correctly, there's no way to fetch all of the stats of the players on my team if my team has more than 25 players? Is there a workaround that doesn't involve a collection?

**Comment by whatadewitt** [comment]
@petegriffith You could get all of the players individually and query player.stats with their ids, but it would be easier to use the players.teams collection with your team key, and then just use the "start" filter and subresource to get each of the pages you need.

**Comment by petegriffith** [comment]
@whatadewitt Thanks. Can you direct me to the page in the docs that will help me with that approach? For now it looks like the players.teams link is broken https://yahoo-fantasy-node-docs.vercel.app/collection/players/team

**Comment by whatadewitt** [comment]
https://yahoo-fantasy-node-docs.vercel.app/collection/players/teams is working for me when I navigate from the nav, but not directly :|

```
try {
  const players = await yf.players.teams(
    TEAM_KEY,
    {start: _X_},
    ['stats'],
  );
} catch (e) {
  // handle error
}

```
should work... I'll figure out why I can't get there directly!

**Comment by petegriffith** [comment]
Got it, thanks! Two questions: 
- Why can I return all 32 players if I set start to 0? I would have assumed Yahoo limited to 25 to limit bandwidth drain?
- Looks like I can't pass an array of team names as the first argument to get multiple team datasets. If that's the case, why is the returned dataset an array of one object?

**Comment by whatadewitt** [comment]
You need to use the team keys, which would be like mlb.l.LEAGUE_ID.t.TEAM_ID

As far as 32, that would be a question for Yahoo! Maybe it’s a happy
accident or it’s set to return all players with that particular call?

**Comment by petegriffith** [comment]
Yep, sorry, I am trying to use the team key as you say, not the team name. When I add any more than one team key to an array, I get a TypeError:

`TypeError: Cannot read properties of undefined (reading '0')
    at mapStats (C:\Users\XXXXXX\Dev\Baseball-project\kaku-server\node_modules\yahoo-fantasy\helpers\playerHelper.mjs:41:30)`

**Comment by whatadewitt** [comment]
That sounds like a bug… I will investigate

**Comment by whatadewitt** [comment]
@petegriffith indeed there was a bug on the docs site that has been resolved. hope you find what you're looking for!!
