### ISSUE TITLE
Players.Leagues Doc Is Not Pluralized

### ISSUE THREAD

**Issue by blark012** [whatadewitt/yahoo-fantasy-sports-api#93]
https://yahoo-fantasy-node-docs.vercel.app/collection/players/league should be 'leagues'. In the collection drop down it league needs to be pluralized as leagues. In the 'How to use' section the code references yf.players.league and it needs to be yf.players.leagues. 

This app is amazing! Thank you!

**Comment by whatadewitt** [comment]
Good eye! I am updating that now!
