### ISSUE TITLE
Handling Secure Connection during Authentication

### ISSUE THREAD

**Issue by jimweigandt** [whatadewitt/yahoo-fantasy-sports-api#99]
I'm not sure if this is a specific question with the Yahoo API or falls under more of a general programming umbrella, but how do you handle the second leg of authentication to the Yahoo API while on localhost?

I get to the point where I agree my app to have access to the leagues I'm in, but upon hitting the callback, I get an error in Chrome that says "This site can't provide a secure connection" with an ERR_SSL_PROTOCOL_ERROR. I assume it's because my localhost is running http instead of an https and when it tries to redirect it fails since it isn't secure. I'm also using Next.js as well, similar to your docs website for the API.

I've been through a ton of articles trying to set up local certificates associated with my localhost but haven't been able to get it to work.

Feel free to close this if it seems like it falls out-of-scope of this specific project, but figured I'd ask anyways just to see!

**Comment by whatadewitt** [comment]
I just generate an SSL cert and run the localhost server over HTTPS.

Something like this: https://medium.com/@greg.farrow1/nextjs-https-for-a-local-dev-server-98bb441eabd7 (note I just Googled this, didn't read it 😆 )

In the past you couldn't even use "localhost" in the callback URLs.

Hope this helps!!

**Comment by ryus08** [comment]
If you are just trying to use it manually, locally, and don't need a non-dev user to get a token themselves, you can set the callback url to `oob` (stands for Out of Bounds). The Yahoo auth flow will stay on Yahoo and display the authorization code. You can copy that into your code/config/disk and continue the flow locally

I.e. hit the following URL with your own client id:

https://api.login.yahoo.com/oauth2/request_auth?client_id=myClientId&redirect_uri=oob&response_type=code&language=en-us

**Comment by whatadewitt** [comment]
That’s right too! Thanks for that!!

**Comment by jimweigandt** [comment]
I hate to re-open this issue since I never responded the first time...as you can tell I've been picking this up and putting it down a lot.

@ryus08 I used your "oob" argument and was able to get the code it returns, however, I'm not sure where I should be inserting it after I get it. Do you have an example of you using that workflow in a call? Is that code the auth code Yahoo needs to let you have access to private leagues? I'm just not sure how to send that request with the credentials that says I can have access. (And maybe this is just a more broad Auth question as well)

Anyways, love this package so much! I've been slowly saving my fantasy league's historic data so I can build a web app with it for my league mates.

**Comment by ryus08** [comment]
Oh, then just continue with the OAuth flow. Here's Yahoo!'s doc for it, you just finished step 3, so start at step 4:

https://developer.yahoo.com/oauth2/guide/flows_authcode/#step-4-exchange-authorization-code-for-access-token

That'll give back an accessToken which you can use until it expires (1 hour I think), and a refresh token you can use indefinitely with step 5 to get a new accessToken

**Comment by jimweigandt** [comment]
After some bumps and hours of tinkering with axios I was able to persist that code and get a fresh authorization token and make some calls!

Thanks for pointing me to that doc, I never actually saw it. And also thank you both for being such a big help. Love this package and glad I was finally able to get authentication working for my app!

For anyone wondering, here is a very basic POST call with `axios` to grab an authentication token from Yahoo:
```javascript
    const response = await axios({
      url: `https://api.login.yahoo.com/oauth2/get_token`,
      method: "post",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: `Basic ${Buffer.from(
          `${process.env.CONSUMER_KEY}:${process.env.CONSUMER_SECRET}`
        ).toString("base64")}`,
      },
      params: {
        client_id: process.env.CONSUMER_KEY,
        client_secret: process.env.CONSUMER_SECRET,
      },
      data: {
        grant_type: "authorization_code",
        redirect_uri: "oob",
        code: "bwjbt8e", // This is the code returned from the first auth GET endpoint
      },
    });
```
